# This is a basic workflow that is manually triggered

name: Deploy and Release via FTP
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "minimal | standard | verbose"
        required: true
        default: "minimal"
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    name: Build and deploy app

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: .

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: Install packages
        run: yarn
        working-directory: ${{ env.working-directory }}

      - name: Compile source
        run: yarn run build
        working-directory: ${{ env.working-directory }}
        env:
          REACT_APP_PUBNUB_PUBLISH_KEY: ${{ secrets.PUBNUB_PUBLISH_KEY }}
          REACT_APP_PUBNUB_SUBSCRIBE_KEY: ${{ secrets.PUBNUB_SUBSCRIBE_KEY }}

      - name: Upload to host via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.WEBGO_SFTP_HOST }}
          port: ${{ secrets.WEBGO_SFTP_PORT }}
          username: ${{ secrets.WEBGO_SFTP_USERNAME }}
          password: ${{ secrets.WEBGO_SFTP_PASSWORD }}
          protocol: ftp
          local-dir: ./build/
          server-dir: /home/www/de.absolutholz.math-practice/
          log-level: ${{ github.event.inputs.logLevel }}
